[metadata]
name = lincl
version = attr: lincl.__version__
description = Use installed Linux commands as Python callables
long_description = file: README.rst
long_description_content_type = text/x-rst
author = Christfried BALIZOU
author_email = christfriedbalizou@gmail.com
license = MIT
license_files = LICENSE
url = https://github.com/christfriedbalizou/lincl
project_urls =
    Source = https://github.com/christfriedbalizou/lincl
    Issues = https://github.com/christfriedbalizou/lincl/issues
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Topic :: Software Development :: Libraries :: Python Modules
keywords = subprocess, command-line, linux, dynamic methods

[options]
packages = find:
python_requires = >=3.10
include_package_data = True
install_requires =
    tomli==2.4.1; python_version < "3.11"

[flake8]
max-line-length = 80
max-complexity = 20
extend-ignore = E203, W503
per-file-ignores =
    tests/*: E501
